### ISSUE TITLE
SEQAN_NO_GLOBAL_EXCEPTION_HANDLER, or the default behavior is unexpected

### ISSUE THREAD

**Issue by nlhepler** [seqan/seqan#1035]
By default, SeqAn installs its own global exception handler, which is a pretty unexpected behavior from a header-only library. To use SeqAn in a library, it requires littering all source files including seqan headers with SEQAN_NO_GLOBAL_EXCEPTION_HANDLER, which is pretty unhygienic.

I would recommend inverting the default behavior to not injecting a handler by default, but doing so in the presence of SEQAN_INSTALL_GLOBAL_EXCEPTION_HANDLER or similar.

**Comment by h-2** [comment]
I agree, what do the others think?

**Comment by rrahn** [comment]
Ok I think in general it makes more sense to explicitly enable something than disabling it.
However, we might want to have then the SEQAN_INSTALL_GLOBAL_EXCEPTION_HANDLER enabled for all demos and tests automatically, which we can do by adding a definition to the seqan_register_tests() and seqan_register_demos() macros respectively. 
For the SeqAn-Apps I purpose to manually enable it via the app specific CMakeLists.txt for each app separately. Otherwise it might not be very intuitive to disable it for a specific SeqAn app if this is wanted at some point? 
@h-2 @esiragusa @weese Further thoughts about this?

**Comment by h-2** [comment]
@rrahn I agree.

**Comment by esiragusa** [comment]
Fixed in #1091 #1092.

**Comment by esiragusa** [comment]
Thanks @nlhepler !
