### ISSUE TITLE
Module for k-mer counting

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#1105]
- Use existing full-text indices.
- Define a k-mer counting interface for sparse sets of k-mers, maybe iterator based?
- Refurbish `countKmers()` from the `alignment_free` module to scale counting beyond 15-mers.
- Remove QGramCounts from IndexQGram (see IndexQGram tutorial: assignment 2 and demo https://github.com/seqan/seqan/blob/master/demos/tutorial/index/index_assignment6.cpp)

**Comment by rrahn** [comment]
@xp3i4 What is the state here?

**Comment by xp3i4** [comment]
I am working on related issues about longer reads.
I think it's better to refurbish the interface later if there exist effective features

**Comment by h-2** [comment]
@xp3i4 What is the state here?

**Comment by rrahn** [comment]
@xp3i4 ping

**Comment by h-2** [comment]
closing this as there was no progress in more than a year.

**Comment by esiragusa** [comment]
😭

**Comment by esiragusa** [comment]
Couldn't you backlog it instead?

**Comment by xp3i4** [comment]
@h-2 @esiragusa This issue was originally to improve the kmer counting of open addressing. But it turns out the performance didn't come to expectations. So, I think it's not very useful just to update the interface now.  I began to look into its details  again last week since the Swift algorithm needs it to speed up, If there is something useful, we can reopen the issue later, I think.
