### ISSUE TITLE
C++14 with travis

### ISSUE THREAD

**Issue by catkira** [seqan/seqan#1189]
Is it possible to make travis compile code with std=c++14 ?

**Comment by h-2** [comment]
We don't even have full c++11 on travis :cry:

But if you can convince them to switch to at least debian stable, we could get GCC-4.9 which has rather complete c++14 support.

**Comment by catkira** [comment]
https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
this looks doable :)

**Comment by h-2** [comment]
@esiragusa can you add the compilers?
I would propose to leave master at building with clang-3.4 and gcc-4.8 (if possible), but change develop to build with clang-3.5 and gcc-4.9.  As per our new inofficial policy we support the last three releases of clang and gcc on develop and the newest release of msvc++ and the previous ones are the oldest of the last three.
I also propose activating **c++11** by default in develop, since that is fully supported by these. As soon as gcc-5.3 is released and we drop gcc-4.9 we can reevaluate siwthcing on c++14 by default, but I fear that msvc++ will be a blocker there (no extended constexpr and some other things in 2015).

**Comment by h-2** [comment]
#1320 will change the behaviour to always use c++14 for everything if available and otherwise use c++11 for everything.

#1327 will add a whole bunch of modern compilers to our travis builds
