### ISSUE TITLE
clear() on FM indices with modified strings is not defined

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan#1228]
typedef ModifiedString<DnaString, ModReverse> TRevDnaString;
	typedef Index<TRevDnaString, FMIndex<> > TIndex;

	DnaString dna("ACGT");
	TRevDnaString revDna(dna);

	TIndex index(revDna);
	clear(index);

``clear(index)`` is trying to clear the text ``clear(getFibre(index, FibreText()))`` which is not defined on ModifiedStrings.

Should we forward the call to the original string and clear it?

**Comment by rrahn** [comment]
I think this is not the desired behaviour for clear.
clear for modified string should do nothing on the host, because the modified string cannot know if other objects depend on the host. It only should set the pointer to the host to null, note that for lightweight objects (e.g., Segments) the object is copied instead of storing the pointer to the host.

**Comment by rrahn** [comment]
Is there no clear function for modified strings?

**Comment by cpockrandt** [comment]
The only clear function for modified strings does not match

    template <typename THost, typename TPositions>
    inline void clear(ModifiedString<THost, ModPos<TPositions> > & me)
    {
        clear(cargo(me));
    }

**Comment by h-2** [comment]
@cpockrandt can you fix it? Thanks.

**Comment by cpockrandt** [comment]
fixed with #1071

**Comment by rrahn** [comment]
Solved in #1071, but will be first included in next major release.

**Comment by cpockrandt** [comment]
Since #1071 was merged, I think we can close this issue ;)
