### ISSUE TITLE
replace __[u]intXt with C99 [u]intX_t

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1315]
- [x] remove platform specific typedefs in `platform_*.h` and add global typedefs from C99 to old-seqan-format (like current gcc)
  - [x] fix test-specific tests and remove platforms specific code from tests
  - [x] search and replace all
``c++
__int8t;
__int16t;
__int32t;
__int64t;
``
with 
``c++
int8_t;
int16_t;
int32_t;
int64_t;
``
and also for the unsigned counter parts **everywhere in the library**.

**Comment by marehr** [comment]
Just some reminders for me:

### 1) remove the file seqan/include/seqan/platform/windows_stdint.h and remove the include
Since C++11 is <cstdint> included.

Remove the include of the header file in
```c++
// Define ISO C9x compliant integers.
//
// For Visual Studio versions more current than 2010, we can use <stdint.h>.  Otherwise,
// we have provide our own bundled stdint.h header.  Using this header can be disabled
// by defining the precompiler variable SEQAN_INCLUDE_BUNDLED_STDINT as 0.

#if _MSC_VER >= 1600
#include <stdint.h>
#else
#if !defined(SEQAN_INCLUDE_BUNDLED_STDINT) || SEQAN_INCLUDE_BUNDLED_STDINT
#include "seqan/platform/windows_stdint.h"
#endif  // #if !defined(SEQAN_INCLUDE_BUNDLED_STDINT) || SEQAN_INCLUDE_BUNDLED_STDINT
#endif  // #if _MSC_VER >= 1600
```
https://github.com/seqan/seqan/blob/develop/include/seqan/platform/platform_windows.h#L90

## 2) Move typedefs from seqan/include/seqan/platform/platform_gcc.h into global seqan/include/seqan/platform/platform.h

remove all platform dependent definitions of __int8, ... in /platform_*.h

```c++
#include <inttypes.h>

[...]

/*!
 * @defgroup StandardIntegers Standard Integers
 * @brief Integers defined globally by the SeqAn library.
 *
 * For protability, SeqAn defines the integers in this group.
 *
 * @typedef StandardIntegers#__int64
 * @headerfile <seqan/platform.h>
 * @brief Signed 64-bit integer type.
 *
 * @signature typedef (...) __int64;
 *
 * [...]
 *
 * @typedef StandardIntegers#__uint8
 * @headerfile <seqan/platform.h>
 * @brief Unsigned 8-bit integer type.
 *
 * @signature typdef (...) __uint8;
 */

// default 64bit type
typedef int64_t __int64;   // nolint
typedef uint64_t __uint64; // nolint

// default 32bit type
typedef int32_t __int32;   // nolint
typedef uint32_t __uint32; // nolint

// default 16bit type
typedef int16_t __int16;   // nolint
typedef uint16_t __uint16; // nolint

// default 8bit type
typedef int8_t __int8;     // nolint
typedef uint8_t __uint8;   // nolint
```
https://github.com/seqan/seqan/blob/develop/include/seqan/platform/platform_gcc.h#L90:

**Comment by marehr** [comment]
was blocked by #1320, because this change requires c++11

**Comment by marehr** [comment]
@h-2 ticket can be closed?

**Comment by h-2** [comment]
yep :+1:
