### ISSUE TITLE
cmake detects c++11, but does not set the compiler flag

### ISSUE THREAD

**Issue by marehr** [seqan/seqan#1326]
`cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ../../seqan`
detects c++11

```
[...]
-- Configuring tests/journaled_string_tree
-- Performing Test CXX11_FOUND
-- Performing Test CXX11_FOUND - Success
-- Try OpenMP C flag = [-fopenmp]
[...]
```

but `make VERBOSE=1` shows that there is no compiler flag set

```
[  0%] Building CXX object tests/graph_types/CMakeFiles/test_graph_types_derived.dir/test_graph_types_derived.cpp.o
cd /projects/seqan-builds/gnu_release/tests/graph_types &&
/usr/bin/g++
-DSEQAN_ENABLE_TESTING=1
-DSEQAN_HAS_EXECINFO=1
-D_FILE_OFFSET_BITS=64
-D_LARGEFILE_SOURCE
-W -Wall -Wno-long-long
-fstrict-aliasing 
-Wstrict-aliasing
-pedantic
-Wno-variadic-macros -O3
-I/projects/seqan/include
-DSEQAN_GLOBAL_EXCEPTION_HANDLER
-o CMakeFiles/test_graph_types_derived.dir/test_graph_types_derived.cpp.o
-c /projects/seqan/tests/graph_types/test_graph_types_derived.cpp
```
=======

A workaround is to explicitly set the compiler flag.

`cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS=-std=c++11 ../../seqan`

**Comment by h-2** [comment]
apps and tests need to explicitly state that they want c++11 with `find_package(CXX11)` and then `set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${SEQAN_CXX_FLAGS} ${CXX11_CXX_FLAGS}")` See for example the sequences' test CMakeLists.
[For the demos I already changed it so that is always included if detected]

As part of #1320 you can have this always be detected as part of FindSeqAn and fail otherwise. Also please get rid of CXX11_CXX_FLAGS and just add respective flags to SEQAN_CXX_FLAGS.
