### ISSUE TITLE
Infixes of Containers of Containers are not Containers of Containers (but should be)

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1678]
pretty much as the title states:
if you have a `StringSet<CharString> s;` then the `ValueType<Infix<StringSet<CharString>>>` should be `CharString`, but instead it is `char`.

**Comment by rrahn** [comment]
Ok, if I am not mistaken only the index module is using infix on StringSets so far.
In this context, however, not an infix of the StringSet, but of some string within the set is requested. This causes major confusion about what an infix of a StringSet should be, because the other way around is a valid assumption.

So here is my proposal:

- [ ] Make ```infix(set, beginPos, endPos)``` and ```infixWithLength(set, beginPos, length)``` behave as standard infix for strings. So it returns a subset of the StringSet specified by the begin and end position (the same for Prefix and Suffix).
- [ ] Add a new convenience function ```stringInfix``` for the index module that models the current ```infix``` and ```infixWithLength``` implementation for StringSets. So it explicitly returns a string infix not a string set infix.

@weese  @esiragusa Or am I missing something with the above mentioned design decisions?

**Comment by esiragusa** [comment]
Do ```beginPos, endPos``` in ```infix(set, beginPos, endPos)``` refer to ```concat(set)```? This disambiguation seems reasonable, although it's not clear to me how StringSet fulfills the container concept.

**Comment by rrahn** [comment]
Hmm, if I get you right, you mean if the given positions are global positions?
As far as I could see (from debugging some index tests) it is a local position (pair of seq id and offset).
Clearly, an infix spanning over multiple sequences does not make sense. So the infix implementations of StringSets merely assemble some sort of convenience functions to access the string content of some string in the set and is only used during index lookups. 
I guess whether StringSets fulfil the container concept is a philosophical question, but not the real problem here. I guess the problem is simply, that the current infix implementation is rather more a implementation detail, than a public interface. In fact, this leads to the current confusion with the usage of Infix for StringSets. Hence, I propose a different interface, which explicitly asks for a string infix and in the case of StringSets requires the StringSetPosition type. However, it would break API 😨 . That's why I am so precautious about it.

**Comment by h-2** [comment]
> I guess whether StringSets fulfil the container concept is a philosophical question

Not really: https://github.com/seqan/seqan/blob/master/include/seqan/sequence/string_set_base.h#L373

> However, it would break API :fearful: . That's why I am so precautious about it.

On the contraray, the changes proposed would bring the implementation inline with the documented API! When worrying about our API, I don't think we need to respect undocumented buggy behaviour unless is actually widely used -- which is not the case here.

**Comment by h-2** [comment]
@rrahn This is fixed, right?
