### ISSUE TITLE
toCString for infix

### ISSUE THREAD

**Issue by schmeing** [seqan/seqan#1713]
Just a minor thing. I want to convert a part of the read id into an integer. I solved it by

`tile = atoi( toCString( seqan::CharString( infix(readID, pos, n) ) ) );`

but I wonder why toCString does not work on the infix, while from the documentation I figured that for example the << operator does.

**Comment by h-2** [comment]
`toCString()` is a wild hack that actually resizes the underlying buffer, appends a numeric zero and returns a pointer to the memory region :open_mouth:
For infixes this is not possible, because they are just a pair of pointers. For a CharString temporary it works of course.

But please instead just use the nice lexicalcast:
```c++
title = lexicalCast<decltype(title)>(infix(readID, pos, n));
```
http://docs.seqan.de/seqan/develop/global_function_lexicalCast.html

**Comment by schmeing** [comment]
Ah, I didn't find that function in my search. That's way more convenient.
Thanks
