### ISSUE TITLE
Check dox for dead links to manual

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1736]
- [ ] http://docs.seqan.de/seqan/develop/specialization_BlastTabularFileIn.html

**Comment by xenigmax** [comment]
Hmm... maybe we need an automatic tester for this.

**Comment by h-2** [comment]
@xenigmax good idea :+1:

**Comment by kneubert** [comment]
I found 11 broken external links in the documentation (html page and line in brackets) :

404: http://seqan.readthedocs.io/en/develop/Tutorial/BlastIO.html [html/specialization_BlastTabularFileOut.html(339)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/PairwiseSequenceAlignment.html [html/global_function_globalAlignment.html(385)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/SeedAndExtend.html [html/global_function_bandedChainAlignment.html(341)]

PROBLEM HTTPConnectionPool(host='gzip.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f936f27f310>: Failed to establish a new connection: [Errno -2] Name or service not known',)): http://gzip.org [html/group_FileCompressionTags.html(101)]

PROBLEM HTTPConnectionPool(host='gzip.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f936f27f310>: Failed to establish a new connection: [Errno -2] Name or service not known',)): http://gzip.org [html/group_FileCompressionTags.html(241)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/BlastIO.html [html/specialization_BlastReportFileOut.html(337)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/BlastIO.html [html/specialization_BlastTabularFileIn.html(338)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/PairwiseSequenceAlignment.html [html/global_function_localAlignment.html(276)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/PairwiseSequenceAlignment.html [html/global_function_globalAlignmentScore.html(287)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/PairwiseSequenceAlignment.html [html/global_function_globalAlignmentScore.html(287)]

404: http://seqan.readthedocs.io/en/develop/Tutorial/IndexedFastaIO.html [html/class_FaiIndex.html(296)]
