### ISSUE TITLE
yara_mapper parse Error

### ISSUE THREAD

**Issue by serosko** [seqan/seqan#1775]
When trying to map fastq reads that contain non-DNA5 characters, the yara_mapper (0.9.6) crashes with a parse Error and Error message "unexspected character 'X' .

**Comment by esiragusa** [comment]
Yara behaves correctly as FastQ files can only contain Dna5 sequences. Where did you get that file? 😉

**Comment by h-2** [comment]
> Yara behaves correctly as FastQ files can only contain Dna5 sequences.

Actually I have just read it up:

> Second comes the sequence line(s), which as in the FASTA format can be line wrapped. Also like FASTA format, there is no explicit limitation on the characters expected, but restriction to the IUPAC single letter codes for (ambiguous) DNA or RNA is wise, and upper case is conventional. In some contexts, the use of lower or mixed case or the inclusion of a gap character may make sense. White space such as tabs or spaces is not permitted.

-- http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2847217/

Maybe our readRecords should automatically set `Iupac<>` as the legal alphabet when reading into `Dna` or `Dna5`? I can currently think of only few cases where this behaviour would not be desirable. And it is a pain to workaround this for every application. 

What do you think, @esiragusa ?

**Comment by rrahn** [comment]
@h-2  Mhmm, I think if a tool says it expects Dna or Dna5 it should terminate if it get's something different.
This is for user safety. They know then what and why it happens, if it fails.
Otherwise, we are back to the original behaviour, that something is read in and than converted implicitly to something else. And the user does not know anything about it and wonders about the results. 
Or did I misunderstand your comment?
As far as I understand the code, you can explicitly say to read a iupac string using the ```IsInAlphabet<TAlphabet>``` metafunction.

**Comment by h-2** [comment]
Closed because inactivity.
