### ISSUE TITLE
bool operator==(const char *lhs, Prefix<CharString>::Type &rhs)

### ISSUE THREAD

**Issue by schmeing** [seqan/seqan#1818]
Is there a reason why this operator does not exist?

`cout << ("Hallo" == CharString("Hallo")) << '\n';`
works fine, but
`cout << ("Hallo" == prefix(CharString("Hallo"),5)) << '\n';`
complains about the missing operator

**Comment by h-2** [comment]
> Is there a reason why this operator does not exist?

Of course there is :smile: 

The problem is, that the conversion does through the CString and our `toCString()` function. The latter is a hack that actually resizes the underlying datastructure, appends a terminator symbol and returns a pointer to the beginning. Now this works for all contiguous data structures, like `seqan::String<>`, `std::string` and `std::vector<>`, but it doesn't work for an infix, because the infix is just a pair of pointers.

It could possibly be done, by having an implicit conversion to the underlying type, but I think that was not done, because it had some other negative side-affects. If you see an immediate solution and could provide a patch / pull-request, I will gladly review it, but for now I would postpone this to SeqAn3 where we want to switch to stl containers and views for infixes anyway.

**Comment by schmeing** [comment]
I don't see the need for the toCString() conversion, but I might have overlooked something as I know nothing about seqans internals.

My current workaround is adding:
```
bool operator==(const char *lhs, const Prefix<const CharString>::Type &rhs){
	return ( '\0' == lhs[length(rhs)] ) && (0 == memcmp( lhs, &seqan::value(rhs,0), length(rhs) ));
}
```
Anything that might go wrong there?

**Comment by h-2** [comment]
> I don't see the need for the toCString() conversion

well the lhs cannot be converted to a prefix of another type, so it would try to convert the rhs to a CString (which doesnt work).

> My current workaround is adding:
> Anything that might go wrong there?

Hm, you might be accessing memory way beyond the end of one of the strings, that's really unsafe. I would try instead:

```c++
bool operator==(const char *lhs, const Prefix<const CharString>::Type &rhs){
    return CharString(lhs) == CharString(rhs);
}
```
Although this will be slower of course.

**Comment by schmeing** [comment]
True, but easily fixed and faster then your suggestion:
```
bool operator==(const char *lhs, const Prefix<const CharString>::Type &rhs){
	return ( strlen(lhs) == length(rhs) ) && (0 == memcmp( lhs, &seqan::value(rhs,0), length(rhs) ));
}
```

**Comment by h-2** [comment]
Yes, for charstrings this works indeed, but for other `seqan::String<>` it wouldn't.

**Comment by schmeing** [comment]
Just to know how much effort it is worth to put in:
When are you planning to release SeqAn3, where this should not be a problem?

I tried to follow the comparison and ended up at the compare_ function line 281 in sequence_lexical. Until there I haven't seen a reason why a const char * shouldn't be supported for the left side, but I might have simply missed it.
Then in the function itself begin() and length() are called on the const char *, which I suppose are not defined, but I got lost searching for the actual definitions of them.

**Comment by rrahn** [comment]
@schmeing We have the comparison operator overloaded for Segments as lhs-operand. So 
```
cout << (prefix(CharString("Hallo"),5) == "Hallo") << '\n';
```
should work.

**Comment by schmeing** [comment]
Awesome. I can confirm that it works. Thanks!

**Comment by h-2** [comment]
@rrahn but why is this the case? And where is it documented?

**Comment by rrahn** [comment]
1. Because it's implemented and 2. why would I know? I didn't write the code 😏
