### ISSUE TITLE
ArgParseArgument list allowing zero or more items?

### ISSUE THREAD

**Issue by bjpop** [seqan/seqan#1825]
Hi SEQAN devs,

I'm writing a program which accepts zero or more FASTA files on the command line, as positional arguments.

If zero files are specified, then it will default to reading from standard input.

I want to write a Seqan argument parser to capture this behaviour. However, I seem stuck with a solution that requires at least one file to be specified.

Here's a sketch of what I have:

```
  ArgumentParser parser(PROGRAM_NAME);
  addOption(parser, ArgParseOption("f", "foo", "Silly example", ArgParseArgument::INTEGER, "INT"));

  addArgument(parser, ArgParseArgument(ArgParseArgument::STRING, "FASTA_FILE", true));

  ArgumentParser::ParseResult res = parse(parser, argc, argv);

```
Notice that isListArgument is set to true.

However, when I run my program, and specify zero positional arguments (but some other option arguments), e.g.

`   $ myprogram -foo 0`

I get the error:

   `Not enough arguments were provided.`

Is there a way to achieve what I want to do?

I thought I might be able to default the ArgParseArgument to be an empty vector somehow, but couldn't get that to work.

If anyone has used the Python ArgumentParser before, the behaviour I want to emulate is the ability to specify nargs='*'

Cheers,
Bernie

**Comment by rrahn** [comment]
Hi @bjpop, I think it would be possible if you could set a default value to the ```ArgParseArgument```, but it seems this is not implemented yet. 
@smehringer  do you know, if we can set a default argument to an ArgParseArgument?
I am just wondering because we can certainly check for it: https://github.com/seqan/seqan/blob/master/include/seqan/arg_parse/arg_parse_argument.h#L997 but I couldn't find a proper function to set a default value.
I think at the moment you can only set it by directly accessing the ```defaultValues``` member.
But than I am not sure how well this default value thing is supported, if there is no public API to set those values. 

In case you can mimic this with options. There it will work with the default value.

**Comment by smehringer** [comment]
Hi @bjpop, sorry for answering that late.

@rrahn I looked into the source code and found the following when I tried to set default values or set the required arguments in a list to zero: (https://github.com/seqan/seqan/blob/master/include/seqan/arg_parse/argument_parser.h#L380)
```
380    // check current argument
381    //  .. arguments should not have default values
382    SEQAN_CHECK(arg.defaultValue.empty(), "Arguments cannot have default values.");
383    SEQAN_CHECK(arg._numberOfValues == 1, "n-Tuple of arguments are not supported.");
```

It seems like arguments do not support what @bjpop would like to implement.

I would recommend the same as @rrahn. Use an ArgParseOption instead. You do not even need to specify a default value but just pass another argument that specifies the required amount of given options ```seqan::ArgParseArgument::STRING, "name", true, REQUIRED_NUMBER)```.
For example:
```
    seqan::ArgumentParser parser("myprogram");

    addOption(parser, seqan::ArgParseOption(
        "I", "Input", "Some intput text (multiple values possible)",
        seqan::ArgParseArgument::STRING, "TEXT", true, 0));

    // Parse command line.
    seqan::ArgumentParser::ParseResult res = seqan::parse(parser, argc, argv);

    if (res != seqan::ArgumentParser::PARSE_OK)
        return res == seqan::ArgumentParser::PARSE_ERROR;

    unsigned count = getOptionValueCount(parser, "Input");
    std::cout  << "there are " << count << " values for the Input specified\n";
```

Side note: If you are using this option to parse input files you might want to consider using ```ArgParseArgument::INPUT_FILE``` instead of a *STRING* because then you are able to specify valid file extensions with ```setValidValues(parser, "option-name", "txt")```. (See https://seqan.readthedocs.io/en/master/Tutorial/GettingStarted/ParsingCommandLineArguments.html#input-output-file-names for more details).

I hope I could help a little :)

**Comment by smehringer** [comment]
Sorry I made a mistake.
The REQUIRED_NUMBER parameter will set the exact number of option values that are expected from the input. Just leave out the last parameter and it will work!
```
addOption(parser, seqan::ArgParseOption(
        "I", "Input", "Some intput text (multiple values possible)",
        seqan::ArgParseArgument::STRING, "TEXT", true));
```

**Comment by bjpop** [comment]
Hi @smehringer 

Thank you for looking into this for me.

I must admit that I switched over to using Boost for command line argument parsing, while not quite as nice as the SeqAn library, was able to support my use case.

I'm still using SeqAn for reading FASTA files.

If I have time, I will try to come back to the SeqAn command line argument library, and try out your suggestion.

**Comment by h-2** [comment]
@smehringer if you think this issue is resolved, feel free to close it.

**Comment by h-2** [comment]
@bjpop of course you can reopen it if you switch back to using the ArgParser and it doesnt work for you ;-)
