### ISSUE TITLE
Generate IndexEsa for fasta/fastq file with multiple seqs [Question]

### ISSUE THREAD

**Issue by ganyfml** [seqan/seqan#1838]
Hi,

I am writing my own code to do the non splicing alignment by using IndexEsa to do the search.
When I creating the IndexEsa index, I get a little confused about how to create IndexEsa index for a fasta/fastq file with multiple seqs inside.

I have a around 2.5GB reference genome(mm9), In below is my minimal working example of creating index and get the result range.

```
  StringSet<Dna5String> seqs;
  StringSet<CharString> ids;
  SeqFileIn seqFileIn;
  open(seqFileIn, "example.fq");
  readRecords(ids, seqs, seqFileIn);

  Index<StringSet<String<Dna5> >, IndexEsa<> > index(seqs);
  indexCreate(index, seqan::EsaSA());

  seqan::Iterator<Index<StringSet<String<Dna5> >, IndexEsa<> >, seqan::TopDown<seqan::ParentLinks<>>>::Type iter_index (index);

  goDown(iter_index, "a");
  std::cout << representative(iter_index) << std::endl;
  seqan::Pair<unsigned> result_range = range(iter_index);
  std::cout << result_range.i1 << ", " << result_range.i2 << std::endl;
```

My question is:
1. In term of the performance efficiency, Is that a good idea to generate suffix array for each chromosome of mm9, and do the search one by on?
2. If 1) is not a good idea, how do I know which chromosome the search result is on?
3. Do you have any comments on the above code, including the index type I am generating....

Thank you in advance!

**Comment by ganyfml** [comment]
I have used the above way to generate index and try to save to a file. But it throw the error in the following:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by rrahn** [comment]
Hi,

to answer your questions swiftly. 1) Well, it depends on how much memory you have available. 
If you build the index over the entire genome, it will be larger than loading one index at a time, but search will be more inefficient, because you have to trigger the same search for every chromosome instead of one time only. To use the string set more efficiently, you should use a http://docs.seqan.de/seqan/develop/?p=ConcatDirectStringSet. 
If the index is built upon a StringSet, it will use as a SAValue a Pair, where the first position is the sequence pos within the string set and the second position, the local position within that string. 
You can use this function http://docs.seqan.de/seqan/develop/?p=VSTreeIterator#VSTreeIterator%23getOccurrences to retrieve an infix over all hits for the current representative. 
Alternatively, I recommend reading this tutorial to learn more about indices and index iterators:
http://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Indices/index.html

Regarding the error message. It seems there is not enough memory available to built the index?
Per default, the index is build in external memory using the $TMPDIR folder. 
On most systems, this might not have enough memory to built the index on. So you might export it to another dir with enough secondary memory for the construction.

**Comment by ganyfml** [comment]
Thanks rrahn! I have looked the tutorial you suggest and ConcatDirectStringSet class, I think it is very helpful! But I still have a little confusion at some places....

1. 
> it will be larger than loading one index at a time, but search will be more inefficient
The inefficient here, you mean efficient, right?

2. 
Since what I use is mainly a suffix tree iterator to go down(never go up), do you think the indices I use (IndexEsa) is right? I found it is really memory consuming, for a 13MB fa file, it generates a 96MB isa, 96MB lcp, 96MB child, which is around 20 times larger than the original fa file. Previously I use IndexWotd to do the search, it consumes less memory, but the size of the index seems to be dynamically changed based my code below:

```
  Dna5Index ref_index(ref);
  indexRequire(ref_index, WotdDir());

  cout << "Size before goDown: " << length(getFibre(ref_index, WotdDir())) << "\n";
  SeqanSAIter iter(ref_index);
  for(int i = 0; i < 10; ++i)
  {
    goDown(iter, 'C');
  }
  cout << "Size after goDown: " << length(getFibre(ref_index, WotdDir())) << "\n";

```
result:
```
ref=ATGTACTACGATATGTCTAGCTACGACTGACACGATCAGCT
query=AGT
./main "$ref" "$query"
Size before goDown: 10
Size after goDown: 16
```

Will this be a performance concern? What indices should I choose?

3. 
I know STAR have one option which helps to load the index into a shared memory and do not release it. So when you do debug, you just need to simply link to that shared memory instead of loading again, which saves a lot of time. Does seqan support such functionality also? If yes, can you briefly tell me how to do it?

Thank you very much for your time!

**Comment by cpockrandt** [comment]
To decrease the index size, you should choose smaller data types. Since you are having less than 4 billion bases, you can use 32bit integers, instead of 64 bit integers, see [here](http://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Indices/StringIndices.html#reducing-the-memory-consumption).

If you want to use a smaller index, I recommend using the [FMIndex](http://docs.seqan.de/seqan/master/?p=FMIndex). Again, you can use smaller integers here as well, see the link above.

> it will be larger than loading one index at a time, but search will be more inefficient

@rrahn really means "inefficient" here. The running time for searching in an IndexEsa or FMIndex does not depend much on the size of the indexed text (except for very small texts that have less cache misses). Searching in one huge index takes about the same time as searching in a **single** smaller index. Therefore, searching in multiple smaller indices will be several times slower than searching in one huge index.

**Comment by ganyfml** [comment]
@cpockrandt Thank you very much for your time and clarification, and sorry for asking so many questions.......
Now it makes much sense to me. I am trying to use the 32 bit integers to decrease the index size....

I am wondering if I use FMIndex instead of IndexEsa, will the speed be slower dependents on what I am doing? (creating iterator and goDown())

Also, does seqan support to load index into shared memory and keep it, so next time I run the program, I wont need to read it to memory again?

**Comment by cpockrandt** [comment]
I'm not very familiar with IndexEsa but from what I've heard our FMIndex occupies less space and is also faster (one reason might be because our research is currently focussed on the FMIndex). Since the FMIndex is a prefix tree, you have to reverse the sequences before building the index).

You can use tmpfs and move your files to `/dev/shm` to avoid loading them from hard disk.

From a theoretical point of view the size of the lcp and childtab files should also decrease. I don't see a reason why we don't do that, it might be a bug. @rrahn, what do you think?

**Comment by cpockrandt** [comment]
@ganyfml I think all questions in here and #1842 are answered so far. If you have still any further questions, feel free to reopen this ticket!
