### ISSUE TITLE
yara_mapper not thread safe

### ISSUE THREAD

**Issue by ktrappe** [seqan/seqan#1886]
I run Yara in a pipeline multiple times, and every now and then Yara would produce an invalid Sam file. This is only detected later in the pipeline or by other programms, meaning Yara writes the file w/o any error or warning. The problem only occurs w/ 24 or 120 (default) threads but not with 1 (or 10 or 20) threads, that is why I think this is an issue depending on the number of threads you use.
I used the latest dev version of Yara (0.9.7 w/ seqan version 2.3.0).

Invalid sam file here means that the Cigar string is sometimes wrong (e.g. 53M150M93M for a 150bp read). Picard also says that there are some other issues.
I tried to attach my toy example and a little bash script that reproduces the error on my machine but it is too big, so let me know if I should send (some of) it (any other way).

**Comment by h-2** [comment]
@ktrappe did you have this problem only with the newest version, or also before?
Do you only have logical errors in the file like wrong CIGAR or also syntactical errors, like a bad format? Can you provide the Picard output?

If it is only in recent versions, it might be due to the bam changes by @rrahn . If it has always been there it is likely to be some problme in Yara and not in SeqAn. @esiragusa could you have a look in that case?

**Comment by esiragusa** [comment]
Hey @ktrappe thanks for reporting this problem. In the past I have seen this rare error of wrong CIGARs with multithreading on. I thought this had been fixed by 0.9.7 but apparently this is not the case... Anyway, could you please try the [latest yara package](http://packages.seqan.de/yara/yara-0.9.7-Linux-x86_64_sse4.tar.xz) instead of the current dev version?

**Comment by ktrappe** [comment]
java-1.8 -jar picard.jar ValidateSamFile I=yaramap_error.sam MODE=SUMMARY
## HISTOGRAM    java.lang.String
Error Type      Count
ERROR:MATES_ARE_SAME_END        6019
ERROR:MATE_NOT_FOUND    18012
ERROR:MISMATCH_FLAG_MATE_NEG_STRAND     31434
ERROR:MISMATCH_FLAG_MATE_UNMAPPED       1923
ERROR:MISMATCH_MATE_ALIGNMENT_START     61512
ERROR:MISSING_PLATFORM_VALUE    1

**Comment by esiragusa** [comment]
Hmm and what about CIGARs?

**Comment by ktrappe** [comment]
samtools view -c yaramap_error.sam
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] parse error at line 1001629
[main_samview] truncated file.

It stops at the first occasion but there are multiple wrong CIGAR lengths. As @h-2 said, this is a logical problem and I think therefore not detected by syntax evaluation through picard

**Comment by ktrappe** [comment]
We have yara_mapper version 0.9.3 on our servers and I tested that one, same issue.
Same for the latest yara package.

**Comment by ktrappe** [comment]
@esiragusa any news on this issue?

**Comment by h-2** [comment]
Closed because inactivity.
