### ISSUE TITLE
Some additions to arg parser

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1946]
- [x] add boolean arguments that can be set with `{on,1,true,yes}` or `{off,0,false,no}`
  - [ ] add INPUT_DIRECTORY and OUTPUT_DIRECTORY which are the same as _FILE but with different label

**Comment by rrahn** [comment]
@smehringer the INPUT_DIR and OUTPUT_DIR are work in progress or should it be put to 2.4?

**Comment by smehringer** [comment]
@rrahn  This was fixed by #1956. 
Input_dir and Output_dir were much easier to add, since by specifying 
" `isInputFileArgument( Input_dir-argument ) = true` " ([here](https://github.com/seqan/seqan/pull/1956/files#diff-b0c140fa651e589e7b5c8653cab13768R431); vice versa for outputdir) the complete behaviour of file arguments now applies for directories as well (as @h-2 requested)
