### ISSUE TITLE
Argument parser --version-check

### ISSUE THREAD

**Issue by bkehr** [seqan/seqan#1989]
Hi,

congratulations for the release! I am currently looking through the new features and changes in 2.3.1.

Can you point me to or add some documentation about the new --version-check option of the ArgumentParser? I found the compiler flag -DSEQAN_DISABLE_VERSION_CHECK listed somewhere hidden on the Tutorial pages but no other documentation. Does it work for programs not distributed as a part of SeqAn?

What was the reason that you made it opt-out by default? To me it seems that opt-in would be a better default.

Cheers,
Birte

**Comment by rrahn** [comment]
Hi @bkehr thank you very much.

We have some documentation about building this feature in different modi. Please see: http://seqan.readthedocs.io/en/master/Infrastructure/Use/CustomBuildSystem.html#seqan-version-check-opt-in and http://seqan.readthedocs.io/en/master/Infrastructure/Use/FindSeqAnCMake.html#checking-for-newer-versions-of-seqan-optional for more information. 
So external app developer can ship their binaries in their preferred mode. Our binaries will be shipped in opt-out mode by default. Anyone compiling from source can switch the behavior using the flags described above. 
But you are right, we will add a more thorough explanation about this feature.

External apps can register their app by simply open a new ticket on github or by writing us a mail to our mailing list. We need the name of the app and the current version. We then add the app to our update site or update it's version number, so that users of this app can also get update information. 

IHTH,
René

**Comment by rrahn** [comment]
@smehringer We should add a more detailed description of this feature into readthedocs for the patch level release. So I switch the milestone.
