### ISSUE TITLE
use two different timeouts in argparser ?

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#2009]
for developer and user? Otherwise the developers might never see the developer info, because she is also user (release binaries) and the other runs always invalidate the timer.

**Comment by smehringer** [comment]
What difference do you propose? About 5 or 10 seconds when in debug mode?

The server response should normally be really fast, since it's only a small request.. so three seconds (current timeout) is already thorough time I think. But I suppose it's not that inconvenient to wait a little longer for developers.
