### ISSUE TITLE
severe performance issues of SIMD code with GCC 4.9

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#2017]
Something is  bugged in GCC 4.9 or in our SIMD code in relation to GCC 4.9.
Lambda run times with SIMD enabled are on average 10-15% better than without SIMD. This is true for GCC>=5 and clang.
For gcc-4.9 however the run-time **increases** by a factor of 2x to over 10x! I am not sure what that amount of slow-down depends on, it seems to just increase with the amout of SIMD that you are doing (in a non-linear fashion).

I have verified this with gcc-4.9.4 on FreeBSD and gcc-4.9.2 on Debian.

I propose 
* [ ] we deactivate SIMD on gcc-4.9 for now [ for 2.3.2 ?]
* [ ] we debug the problem if possible [ for 2.4.0 ?]

**Comment by rrahn** [comment]
@h-2 the first version should do it.

**Comment by rrahn** [comment]
So as for what we know, this is issue comes from the implementation of the intrinsics of gcc-4.9.
This is not really a bug, but a nasty thing, as it remains hidden. 
Since it seems other code changed the structure (@marehr)  and the fix would touch these files, we could as well move this issue to 2.4.

**Comment by marehr** [comment]
Is deactivated #2161, please close
