### ISSUE TITLE
YARA Mapper to output CIGAR strings for secondary alignments

### ISSUE THREAD

**Issue by AlexanderFillbrunn** [seqan/seqan#2055]
I am using SeqAn 2.3.2 with the YARA mapper version 0.9.10 [d80e19a]. I use the YARA mapper to find all occurrences of a query sequence in a library of around 6 million other sequences. Unfortunately all secondary alignments are lacking the CIGAR string, which would be very useful to have for all alignments, not just the primary one. Is that possible or could it be added?

**Comment by rrahn** [comment]
@esiragusa Can you answer this?

**Comment by temehi** [comment]
One particular situation where this creates a problem is when you use samtools to processes the output of yara. Samtools raises a warning that says `mapped sequence without CIGAR` and sets the `read unmapped` flag. So the secondary alignments records are not preserved after any kind of processing using samtools.

**Comment by temehi** [comment]
This is not easily possible with the current design of Yara. Alignments, which is necessary for computing CIGAR strings, are computed for primary matches only. It was decided to against it mainly  because of:

- secondary alignments are rarely interesting,
- computing alignments for all possible mapping location is costly and 
- CIGARS do not contain enough information to discriminate among alignments. Instead, one could use the number of mismatches provided by `NM:i` tag.

Nevertheless, It could be implemented as an optional feature. We welcome pull requests for that.

**Comment by temehi** [comment]
@rrahn @h-2  I will backlog the issue now.

**Comment by lkuchenb** [comment]
I have submitted PR #2309, which fixes this issue.

**Comment by lkuchenb** [comment]
This is fixed now and can be closed
