### ISSUE TITLE
Bug in alignedReadStore ?

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#2063]
From the mailing list:

> Dear seqan developers,
> 
> I realized that they might be a bug in the read counting example of the
> RNA-Seq tutorial. The beginPos and endPos of the AlignedReadStoreElement
> are in the gapped space of the reference genome while the Gff Records
> beginPos and endPos are supposed to be in the ungapped space of the
> reference genome. This relates to my observations that the
> AlignedReadStoreElement does not actually contain any coordinates from the
> ungapped space. This makes the beginPos and endPos of them are different
> from the beginPos and endPos of the BamAlignmentRecord.  And it creates a
> lot of confusion. I would actually suggest adding two extra fields for
> AlignedReadStoreElement, such as beginSourcePos and endSourcePos.

> Below is a copy of the code from the example. I commented on some lines.
```cpp
void countReadsPerGene(String<unsigned> & readsPerGene,
String<TIntervalTree> const & intervalTrees, TStore const & store){
    resize(readsPerGene, length(store.annotationStore), 0);
    String<TId> result;
    int numAlignments = length(store.alignedReadStore);

    // iterate aligned reads and get search their begin and end positions
    SEQAN_OMP_PRAGMA(parallel for private (result))
    for (int i = 0; i < numAlignments; ++i)
    {
        TAlignedRead const & ar = store.alignedReadStore[i];
        TPos queryBegin = _min(ar.beginPos, ar.endPos); // In gapped space
        TPos queryEnd = _max(ar.beginPos, ar.endPos); // In gapped space

        // search read-overlapping genes
        findIntervals(result, intervalTrees[ar.contigId] /*Ungapped
space*/, queryBegin, queryEnd);

        // increase read counter for each overlapping annotation given
the id in the interval tree
        for (unsigned j = 0; j < length(result); ++j)
        {
            SEQAN_OMP_PRAGMA(atomic)
            readsPerGene[result[j]] += 1;
        }
    }}
```

**Comment by h-2** [comment]
@xenigmax have you had time to look at this?

**Comment by xenigmax** [comment]
@h-2
@rrhan

As you all know I am not an expert of this issue. But I just read the tutorial for this user since you have requested.

http://seqan.readthedocs.io/en/master/Tutorial/HowTo/UseCases/SimpleRnaSeq.html

According to the tutorial, it starts with loading of .gff (genes) and .bam (reads) files - not with the alignment.
Hence all the positions have to be based on given files and this can't be the seqan's gap representation. 

I guess he is developing his own application that involves alignment somehow. But this is just my speculation.

I can't find any clue why he think it is wrong.

**Comment by xenigmax** [comment]
@h-2 @rrahn 
I think we can close this. Please check the comment above and let me know your opinion.
