### ISSUE TITLE
arg parser crashes on macOS...

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#2088]
... if one supplies a wrong argument.
E.g.
```sh
./foobar --bax
```
Expected behaviour:
```
foobar: illegal option -- bax
```
Actual behaviour:
```
[1]    82338 abort
```

Only happens on macOS. If one uses only correct arguments, everything is fine.

**Comment by smehringer** [comment]
@h-2 I can't reproduce your error on macOS (10.12.5), g++7.1.0
 Can you provide more information about your case?

**Comment by h-2** [comment]
Hm, it appeared with Lambda, but I don't see how it is related. I configured lambda with the following settings:
```
/opt/local/bin/cmake ../../lambda \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_COMPILER=/opt/local/bin/g++-mp-4.9 \
-DLAMBDA_NATIVE_BUILD=off \
-DLAMBDA_STATIC_BUILD=on \
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
```

**Comment by h-2** [comment]
I was able to reproduce with regular apps like razers3...

**Comment by rrahn** [comment]
@joergi-w can you please look into it?

**Comment by joergi-w** [comment]
Sure! I already looked into it in July together with @smehringer and we could not reproduce it (see above). I will try again and report here...

**Comment by joergi-w** [comment]
The problem is specific to compiler g++-4.9 (tested both homebrew and macports) and relates to all try/catch blocks in the program. We should set the `SEQAN_EXCEPTIONS` macro to false for this compiler. 

This issue is also reported [here](https://github.com/Homebrew/homebrew-core/issues/7837).

**Comment by joergi-w** [comment]
For the case that `SEQAN_EXCEPTIONS` is not defined, the current definition of the `SEQAN_CATCH` macro is wrong. It requires a `constexpr if (false)` such that the following block is not compiled. In the current `if (false)` implementation the (unreachable) code block produces warnings and errors due to undeclared variables. 
We will fix it partially: if `SEQAN_CONSTEXPR_IF` evaluates to `if constexpr` the issue will be fixed. We decided not to re-implement every try/catch block in whole SeqAn for an outdated compiler.

**Comment by h-2** [comment]
TODO: document that we are dropping gcc-4.9 support on mac

**Comment by h-2** [comment]
last todo now covered by #2193
