### ISSUE TITLE
How to obtain the FM range after a search

### ISSUE THREAD

**Issue by xhongyi** [seqan/seqan#2089]
Hi,

Is there anyway to access the pointers into the BWT-location array after an FMIndex query?

I asked in a separate thread but haven't heard back in a while. So I decided to try my luck again (sorry for the spam). If I have the code below:

`#include <iostream>`
`#include <seqan/sequence.h>`
`#include <seqan/index.h>`

`using namespace seqan;`

`typedef FMIndexConfig<void, uint64_t> TConfig;`
`typedef Index<StringSet<String<Dna5> >, FMIndex<void, TConfig> > BWTIndex;`

`BWTIndex fmIndex;`
`Finder<BWTIndex> fmFinder;`

`int main()`
`{`
`    StringSet<String<Dna5> > ref;`
`    appendValue (ref, "GTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTAC");`
` `
`    fmIndex = BWTIndex(ref);`
`    setHaystack(fmFinder, fmIndex);`
`    Iter<BWTIndex, VSTree<TopDown<ParentLinks<> > > > bwt_iter(fmIndex);`
`    goDown(bwt_iter, String<Dna5>("TCATCTCCTTGGC") );`
`    return 0;`
`}`

I will always run into a segfault during execution. I don't think the documentation about how to use Iterator with regard to FMIndex is well documented (the relevant tags are missing from the tutorial).

Can someone tell me how should I iterate the FMIndex? I know I can use find and get FMIndex.range.r1 and FMIndex.range.r2 but they are of mysterious "seqan::Iter<const seqan::CompressedSA<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> > >" type. It's hard to directly record them and store them into a file.

Is there anyway to convert it into an offset (as long unsigned for example) in the BWT-array? I really  need to record the position pairs of the BWT-array positions for a few very specific sequences.

Also is there anyway to directly access these positions using the FMIndex (using the offset information)? I know with BWT one can reconstruct the infix at any position in the BWT-array. Is there an API that I can use? I think I have to somehow manipulate the fibre but that information is also unavailable from the tutorial.

Thanks!

**Comment by xhongyi** [comment]
I found a hacky way of achieving this:

From experiment, I think the order goes A->C->T->G. Therefore  fmFinder.range.i1 after find(fmFinder, 'A') will simply be the first entry of the BWT-array.

With that, all subsequent positions, relative to the first entry, in the BWT-array can be computed by simply subtracting fmFinder.range.i1 - first_entry_pos (first_entry_pos is simply the first entry of the BWT-array).

The idea of Fibre is still kind of confusing but I think it is a pointer to some table stored somewhere. Still not very clear how to directly access the Fibers.

**Comment by cpockrandt** [comment]
The code you provided does not throw any segmentation fault on my machines and it looks fine. But if you use the Iterator instead of the Finder, you can remove the Finder object and setHaystack function. There is no need to use both at the same time.

If you're interested in accessing the suffix array range, etc., I would recommend using the Iterator instead of the Finder.

    #include <iostream>
    #include <seqan/index.h>
    
    using namespace seqan;
    
    int main()
    {
        typedef FMIndexConfig<void, uint64_t> TConfig;
        typedef Index<StringSet<String<Dna5> >, FMIndex<void, TConfig> > BWTIndex;
    
        StringSet<String<Dna5> > ref;
        appendValue(ref, "GTGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCAGCAGCTGGACCCCTAC");
        BWTIndex fmIndex(ref);
        Iter<BWTIndex, VSTree<TopDown<ParentLinks<> > > > bwt_iter(fmIndex);
        std::cout << goDown(bwt_iter, String<Dna5>("CGGTTCCTCTACT")) << std::endl;
        std::cout << value(bwt_iter).range << std::endl;
    
        return 0;
    }

range is a tuple where you can access the left suffix array range with `range.i1` and the right one with `range.i2`. Don't forget to reverse the pattern or the text, otherwise goDown() doesn't find anything and returns false.

**Comment by xhongyi** [comment]
@cpockrandt 
Thanks for the reply!. For bidirectional BWT, is there a way to access both the FWD and REV ranges?

P.S: I have sent you a code snippet which generates segfault.

**Comment by cpockrandt** [comment]
I just realized that there is an official interface for retrieving the range for unidirectional indices:

        std::cout << range(bwt_iter) << std::endl;

You should use the range-function instead of accessing the member (what I suggested above) since the implementation or naming could change in the future (which is very unlikely but it would be cleaner code).

For the bidirectional index there is no official function (yet) but you can still do it 😃
`_iter(bwt_iter, Fwd())` respectively `_iter(bwt_iter, Rev())` returns the underlying unidirectional indices.

        std::cout << range(_iter(bwt_iter, Fwd())) << std::endl;
        std::cout << range(_iter(bwt_iter, Rev())) << std::endl;

**Comment by xhongyi** [comment]
@cpockrandt Thanks! Worked.
