### ISSUE TITLE
What's the size of Iter<BWTIndex, VSTree<TopDown<ParentLinks<> > > >? Does it dynamically allocate storage somewhere?

### ISSUE THREAD

**Issue by xhongyi** [seqan/seqan#2202]
Hi,

I'm having some mysterious trouble with managing the memory footprint of Iter<BWTIndex, VSTree<TopDown<ParentLinks<> > > >.

In short, I have two vectors of Iter<BWTIndex, VSTree<TopDown<ParentLinks<> > > >.
The total **capacity** (not size, but capacity of STL vector) of both vectors is around 400M. I tried to measure the size of each Iter, by sizeof( Iter<BWTIndex, VSTree<TopDown<ParentLinks<> > > >), which returns 224.

That means with 400M * 224 is about 89G. With some give-or-take overhead with the allocator, I would imagine it goes a bit above 100G or maybe at worst 180G. Yet I see almost 1T memory usage.

Did I miss something? I checked with valgrind and there is no memory leak. Does Iter generate some extra storage somewhere else? Maybe in the FMIndex of the Fibre (I never really understood the role of Fibre...)?

Appreciate your feedback!

A little bit about the reason why I'm doing this. I wanted to do a breath first travel of the suffix tree and label each node a unique integer following top-down, left-to-right ordering. However, I also want to keep track parent-children information. That requires me to keep two vectors (sort of like FIFOs) to store Iterators.

Would love to know better ways to handle this.

I'm also profiling with valgrind right now to see a breakdown of memory footprint.

Happy New Year!

**Comment by cpockrandt** [comment]
Hi @xhongyi,

the iterator with parentlinks stores a seqan::String of suffix-array positions, etc. So the size of the Iterator should differ depending on the depth in your suffix tree. I guess that's why you reach more than 100G.

How about building a suffix tree yourself while traversing the implicit suffix tree (using goDown and goRight on the iterator), numbering the nodes in your tree and only storing the iterator (without parent links) in each node. Then you wouldn't waste space on redundant data and the size of each node is constant.

There are ways to assign unique id's to nodes efficiently but it is not implemented in seqan. The SDSL (which we are going to use in seqan 3) supports it (see methods `ìd(node)` and `inv_id(id)` [here](http://algo2.iti.kit.edu/gog/docs/html/group__cst__sada__tree__methods.html)).

🎆 Happy New Year! 🎆

**Comment by xhongyi** [comment]
Yeah I was wondering something like that. Seems like it keeps track of a history linked list so that it can goUp().

Thanks for the suggestion! I will take a look at SDSL.

**Comment by xhongyi** [comment]
Moving to seqan3 seems to be a daunting effort! Wish you best of luck! Will definitely try it out when it comes out.
