### ISSUE TITLE
"Unknown/missing" QUAL field value in a BAM file is read in incorrectly; works correctly for SAM

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan#2230]
In a SAM file, an asterisk ("*") in the QUAL field (11th column) indicates that quality information for the read is missing or unknown.  When reading such a record with `readRecord()`, the `qual` member of the `BamAlignmentRecord` is set to an empty `CharString`, just as the docs state.  But when the equivalent record in a BAM file (where an "unknown/missing" QUAL field is represented as a series of 0xFF byte values) is read in, the `qual` member is instead set to a number of space characters equal in length to the sequence length.  This obviously causes problems round-tripping, etc.

The attached MWE simply reads a SAM or BAM file from stdin, and writes all of its records verbatim to stdout.  The attached SAM file x.sam has a single 11-base-pair sequence, and the attached BAM file is just the equivalent in BAM format (produced by `samtools view -b < x.sam > x.bam`).  Running the code with either file on stdin should produce identical output (provided BAM support has been configured using `SEQAN_HAS_ZLIB`), but the BAM input produces 11 spaces in the rightmost column instead of a "*" character.  (I also output the `qual` member to stderr to determine whether the bug was in `readRecord()` or `writeRecord()`: the spaces appear here already, so the problem must be in `readRecord()`.)

The problem occurs with SeqAn version 2.3.1 as installed by the Ubuntu package libseqan2-dev version 2.3.1+dfsg-3ubuntu1.  I scrolled through 3 pages of bugs with the search terms "is:issue BAM" and didn't see any (open or closed) similar issues.
[seqan_sam_bam_bug_report.zip](https://github.com/seqan/seqan/files/1643554/seqan_sam_bam_bug_report.zip)

**Comment by smehringer** [comment]
Hi @wtwhite,

thank you for reporting this and for your detailed description!

I could reproduce your issue and it might be a bug regarding our sam/bam conversion.

Although I'm not too familiar with the BAM format, I think the quality string in BAM must be always the same length as the sequence length, otherwise decompression is tedious.
Therefore, when reading in a BAM file in seqan, the record.qual string has length 11 in your example. Now, when writing out a SAM format we test whether the string is `empty` [here](https://github.com/seqan/seqan/blob/master/include/seqan/bam_io/write_sam.h#L205), which probably returns false because the record.qual has a length != 0 and thus the empty string is printed instead of `*`.

Side Note: If you change your MWE to output in `Bam()` format (line 13) and pipe the cout into a new bam file `./test_sam_bam_bug < x.sam > y.bam` then samtools view prints out y.bam with the asterisk again. 

Looks like a small bug to me. @temehi what do you think?

**Comment by h-2** [comment]
@smehringer I think your analysis is correct. According to the spec for SAM `*` indicates "not present" and for BAM a string of length of the sequence and all bytes == `0xFF` indicates "not present". Therefore SeqAn should check upon reading the BAM quality string, whether all bits are set and if yes return an empty string, not a string of `0xFFFFF...`.

Can you fix that for the release, aka asap?

**Comment by smehringer** [comment]
Sure  :hourglass_flowing_sand:

**Comment by wtwhite** [comment]
Hi @smehringer, @h-2,

Thank you very much for looking at this and fixing it!  :)

**Comment by smehringer** [comment]
@wtwhite Your welcome :) Thanks for catching it.
