### ISSUE TITLE
Unclear effect of vertex or edge deletion on Graph descriptors and property maps

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan#2243]
I have an undirected graph stored as a `Graph<Undirected<int>>`, and would like to delete some of its vertices and edges, but am not sure whether vertex and edge descriptors, and property maps based on them, will remain valid.  I think that whatever guarantees are made (or plausible guarantees that are not made) here needs to be documented, but I couldn't find any in either the [`Graph` reference page](http://docs.seqan.de/seqan/master/?p=Graph) or the [tutorial page](http://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Graphs.html).

(In case no guarantees are made: Does this really mean that if I want to delete, say, some vertices in a Graph that has associated vertex property maps, then the only correct way to do so is to build a fresh copy of the graph and property maps that do not contain the vertices I want to delete?)

Related minor issues:

* The [`Graph` reference page](http://docs.seqan.de/seqan/master/?p=Graph) doesn't mention the metafunction `VertexDescriptor<TGraph>::Type` (even though it appears in the tutorial).
* The documentation for `removeVertex()` doesn't state whether or not incident edges are removed automatically.
* AFAICT, I may not assume anything about vertex and edge descriptor types.  But knowing, for example, that (at least in the absence of deletions) they are consecutive integers starting at 0 (as they seem to be) would make some things much more efficient, by avoiding the need to populate a separate `std::unordered_map<VertexDescriptorType<TMyGraph>::Type, int> sequenceNumberForDescriptor` or similar in order to be able to get the "time" at which a vertex was created.
* The tutorial page shows a call to `resizeVertexMap()` before any calls to `assignProperty()`.  It would be helpful to also mention the general requirement in the documentation for `assignProperty()` -- that is, that a property map must be manually resized (with a call to `resizeVertexMap()` or `resizeEdgeMap()`) between a call to `addVertex()` or `addEdge()` and a call to `assignProperty()`.
* `Graph` apparently implements the ContainerConcept, so it should provide a function `appendValue()`, but it is not clear what the "element type" of a `Graph` is -- vertices, edges or something else?

**Comment by wtwhite** [comment]
I've been grovelling through the layers of abstraction for a while and have some notes that are hopefully useful to others.  **TL;DR: For undirected graphs, it seems that vertex and edge descriptors remain valid across deletions** -- but that considerable machinery is in place to allow a descriptor-invalidating deletion policy to be used instead, perhaps as simply as by editing graph_interface.h to change a `true` to a `false`.  To me this suggests that the original intent of the design was to avoid committing to a particular policy, so it's probably unwise to rely on the above "default settings" unless you have to.

At least for `Graph<Undirected<TCargo, TSpec>>`, which is defined in graph_impl_undirected.h, vertex and edge descriptors are allocated (in a potentially very configurable way) by [IdManager](http://docs.seqan.de/seqan/master/class_IdManager.html)s, and the concrete IdManager types used for a given concrete graph type `TGraph` are determined by the metafunctions `VertexIdHandler<TGraph>::Type` and `EdgeIdHandler<TGraph>::Type`.

Then, in graph_interface.h, we have:

```
template<typename TSpec>
struct EdgeIdHandler<Graph<TSpec> > {
    typedef typename EdgeIdHandler<typename EdgeType<Graph<TSpec> >::Type>::Type Type;
};
```

That is, it forwards the EdgeIdHandler type of the given graph's edge type.  These are actually defined further down for "known" graph types:

```
template<typename TCargo, typename TSpec>
struct EdgeType<Graph<Undirected<TCargo, TSpec> > > {
    typedef EdgeStump<TCargo, true, true, true, TSpec> Type;
};
```

According to [the docs](http://docs.seqan.de/seqan/master/class_EdgeStump.html), the definition of `EdgeStump` is:

```
template <typename TCargo, bool IS_LIST, bool STORE_SOURCE, bool STORE_ID, typename TSpec>
class EdgeStump;
```

meaning that, at least for `Graph<Undirected<TCargo, TSpec>>`, `STORE_ID` is "hardwired" to `true`.  This will turn out to be what causes vertex and edge descriptors to remain valid across deletions.

Now we want `EdgeIdHandler<EdgeStump<TCargo, true, true, true, TSpec>>::Type`.  This is in graph_base.h:

```
template<typename TCargo, bool TList, bool TSource, typename TSpec>
struct EdgeIdHandler<EdgeStump<TCargo, TList, TSource, true, TSpec> > {
    typedef IdManager<typename Id<EdgeStump<TCargo, TList, TSource, true, TSpec> >::Type> Type;
};
```

(There is also a definition with the same list of type arguments to `EdgeStump`, except with the 4th type parameter `false` instead of `true`.)

`Id<EdgeStump<TCargo, TList, TSource, true, TSpec> >::Type` was hard to track down, but it appears to be defined in basic_type.h as plain `unsigned int` for any non-const argument type.  Thus we are now looking for the definition of `IdManager<unsigned int>`.

Finally, there are two specialisations of `IdManager` in graph_idmanager.h: the first takes any non-`void` first parameter type, while the second handles the `void` type.  The first one, which is accessed here, has methods `obtainId()` and `removeId()` that make it clear that descriptors will remain valid across deletions -- basically, they manage a free list of IDs; the typical alternative implementation, which *would* invalidate descriptors, would shunt remaining objects forward over the top of deleted objects.  FWIW, `IdManager<void>` does *not* appear to be this alternative implementation, but rather a stripped-down implementation that will work only if vertex/edge creation and deletion happens in a LIFO way.

Side notes
---
* There seems to be a minor memory leak in `releaseId()`: If multiple vertices (say) are created, and then all deleted in the same order, then the final `releaseId()` call will only shrink the capacity of `data_in_use` by 1 element (instead of removing all elements, which is desirable, and also what would occur if vertices were deleted in reverse order of their creation).
* Actually the above problem causes a **real bug** in `idCount()`, which relies on `length(data_in_use)` being accurate.

**Comment by hannespetur** [comment]
Maybe someone in the SeqAn team can verify, but I think you are absolutely correct. All member functions of the seqan::Graph will assume that the graph is valid (nothing is associated with a non-existing vertex) and implicitly make the graph valid after it is called. These implicit operations should probably be better clarified in the docs. This is not true in some other graph libraries, for example in Boost.Graph you need to explicitly call the `void MutableGraph::clear_vertex` method with the `void MutableGraph::remove_vertex` method to keep the graph valid.

But as for your side note, I don't think `releaseId` is not leaking memory or there is a bug in `idCount`. `releaseId` is implemented in this way because the underlying data structure of `data_in_use` is a `seqan::String`, in which it is expensive to remove any element except for the last one. So when an element needs to be removed from inside the string it is instead appended to `data_freeIds`. Therefore, `length(data_in_use) - length(data_freeIds)` should be the correct amount of IDs.

Best,
Hannes

**Comment by rrahn** [comment]
Hi I am truly sorry for coming back to you so late. 
First of all I'd like to thank you for diving deep into the code trying to get to the bottom of it. 
Unfortunately, the original authors of this module are not maintaining it anymore, hence it can take some time for us to investigate on your issues. 
But if I am not mistaken, deleting a vertex or an edge from the Graph should not invalidate the other descriptors and property maps. Otherwise, what would be the purpose of them? Regarding the deletion of an edge while iterating over the graph I am not sure what the implementation actually does. 
No matter how it is in the current state it should follow the behaviour of the `std::set`, which itself is just a graph, right: 
> References and iterators to the erased elements are invalidated. Other references and iterators are not affected.
> The iterator pos must be valid and dereferenceable. Thus the end() iterator (which is valid, but is not dereferencable) cannot be used as a value for pos.

So we have to investigate, whether there is a bug (we could fix that), there is a general design issue (we might not be able to fix this), this is done on purpose for whatever reason (we won't change it).
In any case we will remark our findings and usage hints in the API documentation.

@joergi-w can you please take a look into it.

**Comment by wtwhite** [comment]
Thanks everyone for looking into this, I realise it's not something that can be solved in 5 minutes!  :)

@hannespetur: I checked `releaseId()` again and you are right that there is no correctness issue there, sorry about that.  There's still an opportunity for more efficiency, but I now think it's minor.  To clarify, I wasn't suggesting that elements should ever be deleted from the middle of `data_in_use`, rather that when we detect that we are releasing the final element, instead of removing only it, a loop could scan back down from the end of `data_in_use`, removing all trailing elements until we hit one that is in use.  (The function, though usually O(1), is already worst-case O(n) because it contains a call to `appendValue()` that could force an array resize, so we wouldn't lose anything with this change.  It would remain amortised O(1), since every element deleted in this "end-nibbling" scan had to be created.)

@rrahn: Thanks for the info.  I was also thinking that it would be crazy to have descriptors that are invalidated by operations on other vertices, but SeqAn docs are pretty good about documenting even "obvious" properties of things, so if nothing is mentioned about this, maybe I really ought not to assume anything...  Anyway, `std::set`-like behaviour seems a very reasonable design goal, so I hope that's what is actually implemented :)

**Comment by h-2** [comment]
We are not doing any structural changes to SeqAn2 anymore. If you feel that this is a serious showstopper that needs fixing, please re-open!
