### ISSUE TITLE
q-gram match with 'N's

### ISSUE THREAD

**Issue by ztayyebi-wcm** [seqan/seqan#2335]
I have hashed my reads with a q-gram index and I'm using SWIFT to find hits in the reference. I get a lot of hits with all-'N' segments of the genome. how do 'N's match with k-mers that have no 'N's?

**Comment by smehringer** [comment]
Hi @ztayyebi-wcm,

Thanks for using SeqAn.

I am no expert on the index module but I think that it is implementing the biological meaning of the letter `N`, which is that `N` matches any base. So this is expected behaviour in my point of view. Does this cause you any problems?

**Comment by ztayyebi-wcm** [comment]
Hi,
thanks for your response.
well, aligning with the 'N's doesn't give me any information so maybe I should just ignore those matches.

**Comment by rrahn** [comment]
Mhmm, if I remember correctly, there was a repeat masking integrated into the Finder. I also have seen strategies to treat Ns differently in other parts of the Finder. Not sure if that works for the swift as well. @eseiler can you investigate this. I can give you some pointers. But in general an alternative would be to randomize consecutive regions of N‘s as you would not expect to find any hits in a complete random sequence given a not to small q-gram length. And can you give us a small code example of how you call the filter?

**Comment by eseiler** [comment]
Swift offers a option for repeat masking.
Let's consider these lines from the [tutorial](https://seqan.readthedocs.io/en/master/Tutorial/HowTo/Recipes/FilterSimilarSequences.html?highlight=swift):
```cpp
    typedef Finder<TReadSeq, Swift<SwiftSemiGlobal> > TFinder;
```
and
```cpp
        TFinder finder(fragStore.readSeqStore[i]);
```

Instead of using
```cpp
TFinder finder(fragStore.readSeqStore[i]);
```
you can use
```
TFinder finder(fragStore.readSeqStore[i], minRepeatLen, maxPeriod);
```

If you only want to skip the Ns, you can set minRepeatLen to a high value (e.g. the sequence length) to avoid masking any repeats without Ns and maxPeriod to 1. Ns will be reported as repeats and skipped by Swift indipendent of the chosen minRepeatLen.

**Comment by smehringer** [comment]
Solved IMPOV. Feel free to re-open the issue in case there are any more open questions.
