### ISSUE TITLE
Accelerated Alignments

### ISSUE THREAD

**Issue by Lolasdasdasd** [seqan/seqan#2344]
Hi guys!
I was wondering how to make use of SeqAn acceleration. The paper from May 2018 provides insights but gives not examples as far es I can see... My problem is rather simple: I have maaaany peptides that I want to compare in an all-against-all fashion with different alignment parameters - and I want to do it fast. Something like this:

    Score<int> NW1(10, 0, -1, -30); 
    Score<int> HAM(10, 0, -1000, -10000);
    Align<Peptide, ArrayGaps> align;
    resize(rows(align), 2);

    for (many many Peptide pairs (frag1,frag2)){
        assignSource(row(align, 0), frag1);
        assignSource(row(align, 1), frag2);
        int score = globalAlignment(align, HAM); // do something with score...
        score = globalAlignment(align, NW1);     // do something else with score...
    }

Can you help me with that?

**Comment by rrahn** [comment]
Ok some questions to the problem. You have amino acid alphabet but you don't want to use a scoring matrix like blosum or pam? 
I mean that would be really beneficial for vectorisation.
What would be the size of the sequences? I think they are not really long? 
I assume they all differ in their length more or less?
And you want to simply calculate the score to do some pre filtering or do you also need the trace from all alignments?
Are the alignment pairs already pre selected, or would it be imaginable to also add some k-mer based pre-filters?

**Comment by Lolasdasdasd** [comment]
Thanks for you fast reply!
Yes, for some comparison methods I would like to use a scoring matrix but not for all.
Sequences that are being compared always have the same length (ranging between 10-200).
I'm interested in the score and the sequence identity of the alignment. For most cases I do not need the alignment actually (maybe later for other purposes). The choice of fragment pairs is pre-selected.

**Comment by rrahn** [comment]
ok, then I can prepare a snippet that you can use to compute the scores rapidly. 
How is your parallelisation look? Do you already parallelise over some set of alignments? Otherwise, we have integrated this into the alignment function already. I can show you the usage in the snippet.

**Comment by rrahn** [comment]
For the traceback, there is some work in progress to make it really fast for vectorisation, but I guess on the small sequences the current performance would be good already. 
One more question though, are you interested in only the edit? Or do you need the affine gap model for your purpose?

**Comment by rrahn** [comment]
Otherwise, I can prepare something next week after the conference that I am attending.

**Comment by Lolasdasdasd** [comment]
Traceback is not of high priority but gaps and substitution matrix are. I guess the function globalAlignmentScore will do the trick, right?
My current parallelization is simply running the same script with different fragment pairs... But if I can somehow spead it up by comparing the same fragment pairs with different comparison methods in parallel, that would be great already.

**Comment by rrahn** [comment]
So, I prepared a demo to show the usage of the vectorised code. Please find it here: https://gist.github.com/rrahn/e385b43ad72eeebe1ed3e69f06e8d715

I generated one million sequences of size between 10 and 200 amino acids with 20% mutation rate.
I used the seqan-v2.4.0 release and run the parallelised kernels with 20 threads (physical, no hyper-threading). 
I compile it with: `g++-7 -std=c++17 -fopenmp [-msse4|-mavx2] -O2 -I/path/to/seqan-v2.4.0/include simd_align_demo.cpp -o demo` and run it with `./demo 2> scores.csv`
Please note, that I use some c++17 features. So you need at least g++-7 and compile with `-std=c++17`. If this constraint is to high, I can adapt the code to compile at least with g++-4.9.
But it's only the demo. SeqAn does only require g++-4.9 or higher.
The timings are in seconds.

 algo | sequential | sse4_int16 | sse4_int32 | avx2_int16 | avx2_int32 
------|-----------|-----------|-------------|-----------|------------
 simple | 128.625 | 1.15867 | 2.04038 | 0.75954 | 1.16275|
 simple_banded | 57.508 | 0.628194 | 1.20823 | 0.42982 | 0.567995 | 
 blosum62 | 135.472 | ~~~~~ | 2.85715 | ~~~~~ | 1.64583 |
 blosum62_banded | 54.8769 | ~~~~~ | 1.23772 | ~~~~~ | 0.676283 |

In general, the vectorized alignment core expects sets of sequences, while set1[i] is aligned with set2[i]. So there is a one-to-one correspondence. I also suggest to sort the sequence pairs before, by the size of the first sequence. This will more or less have a bigger effect on the vectorised code. 
Unfortunately, there is a bug, when setting the underlying score type for matrix scores to a lower value than int32_t. I will fix that, but this might take until November due to conferences and vacation. 
If there are more questions to the code, please ask me.

**Comment by rrahn** [comment]
And of course if you servers would support avx512 we can even speed it up by a factor of roughly 2 compared to avx2.

**Comment by Lolasdasdasd** [comment]
It took me some time to get to it again... And it works like a charm :) Thanks a lot for your support!
