### ISSUE TITLE
Constructing an EdgeIterator on a Graph with no vertices causes segfault 

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan#2360]
I originally came across this problem when I found that calling `connectedComponents()` on a vertexless Graph caused a segfault.  I've narrowed it down to calling the constructor for an `EdgeIterator` object -- please see the attached MRE.  This breaks a "standard" loop for visiting every edge in a Graph:

```
TGraph g;
...
for (Iterator<TGraph, EdgeIterator>::Type it(g); !atEnd(it); goNext(it)) { ... }
```

(the correct behaviour on a vertexless Graph would be that the loop body executes zero times).  Having even a single vertex in the graph makes the problem go away.

If someone can suggest what "should" happen here, I could try making a fix myself, but I'm wary of making changes in this part of the code as there are many different interacting Graph and Graph iterator types.

[repro_empty_graph_iterator_crash.zip](https://github.com/seqan/seqan/files/2590389/repro_empty_graph_iterator_crash.zip)

**Comment by smehringer** [comment]
Hi @wtwhite,

thanks for reporting this.

Segfaults should never be caused by any usage so this is a definitive bug (if reproducible). I don't know how well the Graph library is maintained though because we will switch to the lemon library for graph related functionality in SeqAn3.

@joergi-w Can you have a look as you are more acquainted with Graphs? Check if we can make a quick fix to avoid the segmentation fault and see if you know what "should happen here" so we can maybe shortly discuss the expected behaviour.

**Comment by joergi-w** [comment]
Initializing an iterator of an empty graph should surely not fail. 

Problem location: The constructor of EdgeIterator accesses the first vertex, while initializing the member `data_edge`. This access fails, if there is no single vertex in the graph. 

Solution: The constructor checks, whether the vertex string is not empty before accessing the first vertex. Furthermore, the iterator of an empty graph must be always in the condition atEnd. I will implement the changes and provide tests to assure the correct behavior.

**Comment by wtwhite** [comment]
Thanks for looking at this!  These changes look good to me.
