### ISSUE TITLE
jumpToRegion cannot locate the alignment when there are few mappings

### ISSUE THREAD

**Issue by canfirtina** [seqan/seqan#2387]
Hi SeqAn team,

I probably discovered a strange bug related to the function "jumpToRegion". I observed that when there are a few mappings to a contig (e.g., 1-2 mappings in my case), jumpToRegion fails to find these alignments. Here are the steps for you to regenerate the problem:

Download a few reads from PacBio
`curl -s http://datasets.pacb.com.s3.amazonaws.com/2014/c_elegans/additional_data/2590969/0002/Analysis_Results/m140928_104939_ethan_c100699582550000001823139903261541_s1_p0.3.subreads.fasta | head -5000 > pacbio.fasta
`

Download the contigs:

`curl -L -o assembly.fasta http://datasets.pacb.com.s3.amazonaws.com/2014/c_elegans/40X/polished_assembly/polished_assembly.fasta`

Align the reads to the contigs and sort. I used minimap2 (the latest version).

`minimap2 -x map-pb -a assembly.fasta pacbio.fasta | samtools view -h -F4 | samtools sort -m 16G -l0 > alignment.bam`

Index the BAM file:

`samtools index alignment.bam`

Now when I use SeqAn 2.4.0 and minimap2, I see that a read aligns to the contig "unitig_64|quiver". When I try to jump to the region using the function jumpToRegion, "hasAlignments" is set to false. I set the start and end regions as 0, and length of the contig, respectively. However, when I call "readRecord" function to read the alignments from the BAM file, it clearly shows the mapping to the contig unitig_64|quiver. I checked if my indexing is corrupted but when I call the following commands, I can also see the mappings:

`samtools view alignment.bam "unitig_64|quiver"`
`samtools idxstats alignment.bam`

Thus, I believe that all the inputs are probably correct but there is a strange bug in "jumpToRegion" when we have fewer mappings to a contig. Note that I do not observe this error when there are many mappings to a contig. Thanks.

**Comment by canfirtina** [comment]
Here is also the line of code where I use this function:

https://github.com/CMU-SAFARI/Apollo/blob/b39015a3707149563e2de5d069f1a7b569ca0f9c/src/main.cpp#L1124

**Comment by rrahn** [comment]
Hi thanks for reaching us to us. 
Indeed it is possible that jumpToRegion does not work properly for PacBioReads since the reads have a very heterogeneous size. It is more suitable for short reads with homogeneous sizes. We have another function called viewRecords. Unfortunately it does not show in our documentation. We will have a look. But in case here is the interface:
```cpp
void viewRecords(TContainer & resultContainer,
                 FormattedFile<Bam, Input, TSpec> & bamFile,
                 BamIndex<Bai> const & bamIndex,
                 int32_t const refId,
                 uint32_t regionStart,
                 uint32_t regionEnd)
```
The first argument is a container (e.g. seqan::String) over `BamAlignmentRecord`s, which contains the respective records of the alignments that overlap with the region. Can you try this and check if this works already?

**Comment by canfirtina** [comment]
Hi @rrahn . Thanks for the quick response. Unfortunately, I am unable to locate the _viewRecords_ function anywhere in the entire project folder. Is it only located in older commits? I see that you added some unit tests for viewRecords in the earlier commits (https://github.com/seqan/seqan/commit/3f0ee71ff03e2b5eace7854cf579580b8c91fe60) but neither the unit tests nor the function itself is present in the latest commit. Is it safe to get the older code and use this function?:

https://github.com/seqan/seqan/blob/3f0ee71ff03e2b5eace7854cf579580b8c91fe60/include/seqan/bam_io/bam_index_bai.h#L228-L234

**Comment by rrahn** [comment]
Mhmm, the feature is newer than I thought. It is not available in the current master but only in develop. Sorry, I kind of lost track of these things after we started working heavily on SeqAn3. Can you work on develop instead? We will probably don't have another release before fall.

**Comment by canfirtina** [comment]
It looks like _viewContainer_ function available under develop solved my problem. Thanks for the suggestion.

I also have an idea that you may want to consider. I had been using the _jumpRegion_ function to point out to the first occurrence of an alignment for a specific contig (i.e., refId). If there is at least one such alignment, I usually use a buffer to read a _limited number of alignments_ starting from the region that I want to process. This helps me to manage the number of items I work because there can be many alignments (even billions of alignments?) to a specific contig for its entire region. 

However, I noticed that viewRecords will return all of the alignments given a region (i.e., region = 1-based [regionStart, regionEnd]). Although it is possible that one can call the _viewRecords_ function by sliding region of interest to use it like a buffer, this still does not quite help me to manage the maximum number of items that I want to work at a time. It would also be great if we can specify _offset_ and _size_ values where the _size_ is the maximum number alignments that will be returned when _offset_ many alignments are skipped in the specified region of the contig. If there is already a function or way of achieving this when using viewRecords, you can of course ignore this suggestion.

Thanks for the help again.

**Comment by rrahn** [comment]
Glad it did help and thank you very much for the suggestion. The problem with jump to region alone is that you find the first alignment that overlaps with the specified region, but with long reads it could happen that a lot of reads coming next would not intersect with the region because they are smaller compared to the first one that matches. 

So viewRecords is actually what you want. In SeqAn3 we will add this feature as a lazy view. In this case you don't buffer in advance but merely iterate only once over the respective region and you can process all records one by one so that there won't be a huge memory allocation for millions of reads. For SeqAn2 we do have a feature stop but will fix issues. If you have more ideas to improve SeqAn we are welcome to take any feature request on https://github.com/seqan/seqan3. 

> Thanks for the help again.

You are very welcome!
