### ISSUE TITLE
Global alignment is wrong in some cases (Score is correct)

### ISSUE THREAD

**Issue by svnbgnk** [seqan/seqan#2397]
In both cases the alignment with 2 gaps and 1 mismatch should be found. 
Both the first alignment shows 2 gaps and 2 mismatches.
```cpp
    typedef String<Dna5> TSequence;                 // sequence type
    typedef Align<TSequence, ArrayGaps> TAlign;     // align type
    AlignConfig<true, true, true, true> ac;

    {
        Dna5String reference =      "TTTCTATTAATGATCTGTAG";
        Dna5String needle =         "CTACACGATCT";

        TAlign align;
        resize(rows(align), 2);
        assignSource(row(align, 0), reference);
        assignSource(row(align, 1), needle);


        int score = globalAlignment(align, Score<int, Simple>(1, -1, -1), ac);
        std::cout << "Score: " << score << std::endl;
        std::cout << align << std::endl;
    }


    {
        Dna5String reference =      "TTAATGATCT";
        Dna5String needle =         "CTACACGATCT";

        TAlign align;
        resize(rows(align), 2);
        assignSource(row(align, 0), reference);
        assignSource(row(align, 1), needle);


        int score = globalAlignment(align, Score<int, Simple>(1, -1, -1), ac);
        std::cout << "Score: " << score << std::endl;
        std::cout << align << std::endl;
    }
```

Score: 5
      0     .    :    .    : 
        TTTCTA**TTA**A**T**GATCTGTAG 
        -----CTA---CACGATCT----

Score: 5
      0     .    :  
        TTA--ATGATCT
        **C**TACA**C**GATCT
Mismatches are highlighted in bold, I tried to align gaps correctly. I show a better alignment by cutting of the sequence in the front, which was wrongly aligned to.
To make it more clear here is what the first alignment is supposed to look like:
Score: 5
      0     .    :    .    : 
        TTTCTA**T**TA--A**T**GATCTGTAG 
        ----------CTACACGATCT----

**Comment by rrahn** [comment]
Ok, I will have a look at this.

**Comment by rrahn** [comment]
Ok, I took my time to look into it. First of all, why would you expect the second alignment to be as you suggested? The generated alignments are both valid and correct, but if there are multiple optimal alignments than only one of the optimal ones is reported. The second problem is that your sequences are not the same. So the `CTA` pattern exists in the first reference sequence and thus will influence the path that is taken. In this case the suffix of the alignment is longer by one mismatch due to the higher score in the prefix. During the traceback the diagonal is followed as long as possible than the vertical path is preferred over the horizontal path in the traceback matrix. What you suggests is that the first alignment changes the precedence of mismatch and gap. If you want to reach this it has to be reflected within the score. But this will again result in totally different alignments and will end in the same observation for some other examples. 

So it would be good to know what you want to achieve, making this is a defect for you.

**Comment by rrahn** [comment]
@svnbgnk I will close this for now, as I believe it is not a valid issue anymore. Please don't hesitate to reopen the ticket if this is still causing issues for you.
