### ISSUE TITLE
How to get all transcripts of a gene?

### ISSUE THREAD

**Issue by liqg** [seqan/seqan#2398]
I  have read a gtf file using readRecords, I want to get all transcript annotations of a gene id, like this:
```c++
std::vector<TAnnotation::TId > get_all_transcripts (FragmentStore<> store, TAnnotation::TId  gid){

}

```

I am new to c++ and seqan, I have read the document, but I failed, could anyone tell me which part or function of the document I should read. 

Thanks!

**Comment by liqg** [comment]
I realized that the iterator just a struct with a reference to store and an id, I wrote this one:
```c++
std::vector<TId> get_all_transcripts (TStore store, TId gid){
  TTree tree(store, gid);
  SEQAN_ASSERT_EQ(getType(tree), "gene");
  std::vector<TId> out;
  if (goDown(tree)){
    do{
      if(getType(tree) == "transcript"){
        out.push_back(tree._id);
      }
    }
    while(goRight(tree));
  }
  return out;
}
any suggestion for this?
```

**Comment by smehringer** [comment]
Hi @liqg,

we are happy to hear that you are using seqan.

Your solution looks very good but it is hard to tell for sure if it is correct since I don't know the exact types.
Specifically, what are the types `TAnnotation` and `TTree?

You probably already saw that we have a small example tutorial for this?
https://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Store/FragmentStore.html#gene-annotation
If not, does it help?

**Comment by liqg** [comment]
Thanks @smehringer
Sorry for missing the type definitions, here: 
```c++
typedef FragmentStore<>                         TStore;
typedef TAnnotation::TId                        TId;
typedef Value<TStore::TAnnotationStore>::Type   TAnnotation;
typedef Iterator<FragmentStore<>, AnnotationTree<> >::Type TTree;
```

**Comment by smehringer** [comment]
Hi @liqg ,

Thanks for the update. Then your traversal is accurate and should lead the desired result.
Just one remark, use `value(tree)` instead of accessing the `tree._id` member directly.

Do you have any other question or is this issue resolved for you know?
