### ISSUE TITLE
jumpToRegion() failed to retrieve records when posBeg is less than the first record.

### ISSUE THREAD

**Issue by lijinbio** [seqan/seqan#2403]
Hi all,

I am trying to extract chromosome-specific records from an indexed BAM file. However, jumpToRegion() will show hasAlignment as false if beginPos of the query region is less than the first record, and in my case, the query beginPos should be 1. The example is adapted from below link.

https://seqan.readthedocs.io/en/master/Tutorial/InputOutput/SamAndBamIO.html#using-bam-indices

For example, no alignment will report when beginPos = 6 (< 7, and 7 is the first record position in the example.bam). In fact, any values less than 7 will report no alignments, i.e. hasAlignment is false. Can anyone help resolve this problem? Thank you.

Best regards,
Jin

**Comment by rrahn** [comment]
Hi @lijinbio many thanks for writing us. In general in the past jumpToRegion has caused some trouble because it is defined on the first position. If there is no alignment at this position then it assumes correctly that there is no alignment. An alternative solution that should work and is also well defined for long reads is the function `viewRecords`. Here you have to specify the region in which to find the alignments. There is still a missing entry in the online documentation for this function, but we will look into it this week. Thus, I give you a link to a related issue that was fixed by this: #2387. 

I hope this helps. If not please don’t hesitate to come back to us.

The SeqAn Team

**Comment by smehringer** [comment]
viewRecords is documented [here](http://docs.seqan.de/seqan/develop/specialization_BamFileIn.html#BamFileIn#viewRecords) already but only available on the develop branch. We will hopefully release that in to master soon.

**Comment by rrahn** [comment]
Thanks for pointing to it. It is only available after I rebuild the online documentation for develop this week but I forgot notify this threat. As expected we don't have regular builds of the dox anymore. I have it on my list for next week to re-enable it.

**Comment by rrahn** [comment]
@lijinbio I hope the provided solution resolved your questiono? If you don't feel that your request has been answered sufficiently, please don't hesitate to reopen this issue.
