### ISSUE TITLE
Difference between SIMD and serial local alignment

### ISSUE THREAD

**Issue by sarahet** [seqan/seqan#2417]
The local alignment function in SIMD mode includes amino acids that mismatch but do not decrease the score. For example:

```
Query  1    EGLSAQADGSLRQEQVCDALRCSGPHARYTD  31 
             G S      + Q QVCDALRCSGPHARYTD
Sbjct  464  RGTSGV*PHEIEQ*QVCDALRCSGPHARYTD
```

Here, E and R score 0 in the Blossum62 matrix. Therefore, by including them the score stays the same and it is included in the alignment. This does not happen in serial mode, only in the SIMD version. It should probably be avoided to make sure that for example in case of a nucleotide mismatch score of 0 not the whole query gets aligned anyways.

**Comment by rrahn** [comment]
Hi @sarahet thanks for reporting this. Can you do me a favor and give me a small working code snippet for testing? In addition, could you specify exactly what is the expected behavior and what is the observed behavior? Then I can built a test case for this. Many many thanks in advance.

**Comment by sarahet** [comment]
Hi @rrahn 

I have an example [here](https://gist.github.com/sarahet/294e46f5cea8a7ee3d198c863e98489b). First, this computes a normal local alignment, afterwards the SIMD version. This is how we use the SIMD execution in lambda which is not simply the vectorized execution of the ```localAlignment``` function. I actually tried to use this version and it worked as expected (as the serial version). So the problem might be in our specific call of the underlying ```_prepareAndRunSimdAlignment``` function. 

The expected output is:
```
Score = 109
      0     .    :    .    :    .   
        EPCISIYCLYLPVAGLGNLRGCCLPWM
        | || |   |||  | |||| ||||||
        ESCIVIFRHYLPASGMGNLRACCLPWM
```
which is here the output of the serial localAlignment function. Our call of the ```_prepareAndRunSimdAlignment``` somehow leads to this:
```
KEPCISIYCLYLPVAGLGNLRGCCLPWM
NESCIVIFRHYLPASGMGNLRACCLPWM
```

It is the same alignment, except that in the beginning the amino acids K/N are added. In the BLOSUM62 matrix, these two amino acids have a score of 0. This means that also for this alignment the score is the same as for the serial version (109) since it does not get worse by adding this pair. However, it is technically still a mismatch and should in my opinion not be included as it does not improve the alignment.

**Comment by rrahn** [comment]
Thanks for the example. I'll investigate this.

**Comment by rrahn** [comment]
Ok, so I could pinpoint the problem to the config that you pass to the alignment. If you change https://gist.github.com/sarahet/294e46f5cea8a7ee3d198c863e98489b#file-test_local_alignment-cpp-L83 to 
```cpp
    using TAlignConfig  = seqan::AlignConfig2<seqan::LocalAlignment_<>,
                                              seqan::DPBandConfig<seqan::BandOff>,
                                              seqan::FreeEndGaps_<seqan::True, seqan::True, seqan::True, seqan::True>,
                                              std::conditional_t<withTrace,
                                                                 seqan::TracebackOn<
                                                                     seqan::TracebackConfig_<seqan::SingleTrace,
                                                                                             seqan::GapsLeft> >,
                                                                 seqan::TracebackOff> >;
```
it works as expected. Note the difference is in the `TracebackConfig` object which now only computes one of the optimal alignments and not all possible optimal paths for the same alignment (it is not the same as computing all sub-optimal alignments). The question would be whether you really need this option? In general, computing only one optimal path should be more efficient since less comparisons are necessary. 
Independent of that I think you are right that the result should not contain the leading substitution as the score must have been positive already for the local alignment to start there. But then at least the score before should have been positive and should have been also included. So I hope I could help with your particular problem but will investigate the general problem further.

**Comment by rrahn** [comment]
@sarahet I fixed the general issue. Still if not explicitly required I would change the traceback policy above to single trace for performance reasons.

**Comment by sarahet** [comment]
Thanks a lot, we will change to single trace as suggested!
