### ISSUE TITLE
Core Dump (Segmentation fault)

### ISSUE THREAD

**Issue by agakrawczyk** [seqan/seqan#2419]
Hello, 
I was trying to map the sequencing data using yara and after some time of the alignment running without any problems, I got an error: Core Dump (Segmentation fault). I checked permissions to the file and it looks to me like they are the same as for any other successful file. It's a sample containing some human reads and presumably low Cosavirus load (could be that this file contains a lot of repeating regions). However, Bowtie2 didn't have any issues with it. 
This caused much longer run time for the whole pipeline and the significant memory use. Do you have an idea why this could happen? If it's a bug I could try to provide you more information. 
Thank you! 
Best, Aga

**Comment by rrahn** [comment]
Hi Aga, thanks for writing us. 
It looks like a memory issue. To investigate this we would need the files you used, as well as the program options you chose in order to investigate this. Can you also provide us the Yara version as well as the system information you are running on? Many thanks in advance.

**Comment by rrahn** [comment]
Hi Aga, since we did not hear back from you for while now we would like to close this issue for now. Please feel free to reopen it if you feel that there is more we could do.
