### ISSUE TITLE
Browse documentation by module

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#496]
I think the documentation would profit greatly from being browsable by module, e.g. when nothing is entered in the search bar, show a tree-like view on the left that has all the modules; upen clicking on a module the list should be expanded to show the contained dox items, sorted by type.

reasons:
our code and our doc is spread between many files, and while the new interface stuff draws some connections between items, it is still not clear what is where.

people include seqan functionality by including a header file, so this is the most intuitive way to structure functionality from my pov.

**Comment by xenigmax** [comment]
Hmm.  This will take some time... But I will try..

**Comment by rrahn** [comment]
@xenigmax In case we can move this to 2.2.0. It's only dox stuff, so it does not break any of the code.

**Comment by xenigmax** [comment]
@rrahn  Yeah.. I think that's a good idea. 
@h-2  What do you think? Anyway I will be working on it. :)

**Comment by rrahn** [comment]
@xenigmax This is a very nice work.
However, I think we need to postpone this to the seqan 3.0. It does not make sense to mess around with the dox yet. We plan to restructure the module directories anyway. And I think we need much more work to improve the design. At the moment I am not happy with it. Since we all are not the web-developer-kind-of-guys I recommend to change this later.
