### ISSUE TITLE
AminoAcid alphabet is missing character O (Pyrrolysine)

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#864]
Hannes, I'm assigning you because you worked on #762 before. I guess you know how to change the translation tables... :cake:

**Comment by h-2** [comment]
ahhhh, not again :sob:

**Comment by h-2** [comment]
Since this involves changing all the scoring matrices, many tests and some apps, I am not sure I will do it in time for 2.0.1. Or did someone external request it?

**Comment by esiragusa** [comment]
Unfortunately we have to apply it asap as a hotfix, as it's necessary for a cleavage site enumerator in OpenMS.

**Comment by h-2** [comment]
Is thursday soon enough?

**Comment by esiragusa** [comment]
In my case I can still use CharStrings instead of Peptides - but I think this should go into a hotfix anyway... Hmm don't you encounter the same problem as you index the sprot db with Lambda? If you like we can have a look together whenever you have some time. Thanks!

**Comment by h-2** [comment]
> Hmm don't you encounter the same problem as you index the sprot db with Lambda?

Lambda still uses old IO code (...) and since that converts unknown alphabetical to 'X' and 'N' respectively it behaves as desired (O doesn't have values in the substitutation matrices so we will have to hardwire it to behave like X anyway).

> If you like we can have a look together whenever you have some time. Thanks!

The changes are pretty straight forward, but tedious, as can been seen here:
https://github.com/seqan/seqan/pull/762/files

I might be at home tomorrow, but I will definitely be her on Thursday, so we can look into it then,.
