### ISSUE TITLE
Improve Index Iterators tutorials

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#955]
The tutorial at http://seqan.readthedocs.org/en/master/Tutorial/IndexIterators.html should:
- [x] cover IndexSA
- [x] explain trie vs. tree iteration
- [x] mention that the TopDown Iterator without History is meant to be used in _recursive_ algorithms
- [x] show pictures of real suffix trie/trees rather than search trees.

**Comment by esiragusa** [comment]
To be done after merging #1173 #1174.

**Comment by cpockrandt** [comment]
@xenigmax Is this issue up-to-date? It doesn't match the assignment in Trello. I guess I should be working on it?

@xp3i4 Are you currently working on this or planning to?

**Comment by xenigmax** [comment]
@xp3i4 

Please check the overlaps between below two tutorials.
Check #1403 before doing this.

1) http://seqan.readthedocs.org/en/feature-manual-restructure/Tutorial/Algorithms/PatternMatching/IndexedPatternMatching.html
2) http://seqan.readthedocs.org/en/feature-manual-restructure/Tutorial/DataStructures/Indices/IndexIterators.html

**Comment by xenigmax** [comment]
@cpockrandt  
According to Trello, your task is about string index only.

http://seqan.readthedocs.org/en/feature-manual-restructure/Tutorial/DataStructures/Indices/StringIndices.html

Did you make a PR for this?

**Comment by cpockrandt** [comment]
@xenigmax Trello says "String indices: rework together with string iterators". I think string iterators are referring to index iterators? Please correct me, if I'm wrong :smile: 

Since noone could tell me in what way it should be reworked and René is not here, I just checked the index iterator tutorial and didn't rework it.

In my opinion there are no overlaps between IndexedPatternMatching and IndexIterators, I already made some modifications to IndexedPatternMatching. There are no PR because I accidentally pushed to the upstream repository :grin:

**Comment by xenigmax** [comment]
> Trello says "String indices: rework together with string iterators". I think string iterators are referring to index iterators? Please correct me, if I'm wrong :smile:
Since noone could tell me in what way it should be reworked and René is not here, I just checked the index iterator tutorial and didn't rework it.

OK. Then you may need a discussion with Rene on coming Mon(21). I also have no idea about this rework and could not tell you about the direction.

> In my opinion there are no overlaps between IndexedPatternMatching and IndexIterators, I already made some modifications to IndexedPatternMatching. There are no PR because I accidentally pushed to the upstream repository :grin:

All right!

**Comment by cpockrandt** [comment]
@xp3i4: In consultation with @xenigmax, I will work on this issue :smiley:

**Comment by xenigmax** [comment]
Done by #1593 except the last one - pictures.
I move this to 2.1.2

**Comment by h-2** [comment]
What is the state of this? It looks like it is almost done.

**Comment by h-2** [comment]
@cpockrandt ping
